# The name of file which is to be compiled
OBJS = main.cpp

# The name of file after the cpp file is compiled
OBJ_NAME = main

# The name of the compiler
CC = g++

# Compiler flags
COMPILER_FLAGS = -w

#  Linker flags
LINKER_FLAGS = -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer

# Code for compilation
all: $(OBJS)
	$(CC) $(OBJS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME)

